[package]
name = "node-testing"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
fs_extra = "1"
futures = "0.3.21"
log = "0.4.17"
tempfile = "3.1.0"
frame-system = { version = "9.0.0", path = "../../../frame/system" }
node-executor = { version = "3.0.0-dev", path = "../executor" }
node-primitives = { version = "2.0.0", path = "../primitives" }
kitchensink-runtime = { version = "3.0.0-dev", path = "../runtime" }
pallet-assets = { version = "10.0.0", path = "../../../frame/assets" }
pallet-asset-tx-payment = { version = "10.0.0", path = "../../../frame/transaction-payment/asset-tx-payment" }
pallet-transaction-payment = { version = "9.0.0", path = "../../../frame/transaction-payment" }
sc-block-builder = { version = "0.15.0", path = "../../../client/block-builder" }
sc-client-api = { version = "9.0.0", path = "../../../client/api" }
sc-client-db = { version = "0.16.0", features = ["rocksdb"], path = "../../../client/db" }
sc-consensus = { version = "0.15.0", path = "../../../client/consensus/common" }
sc-executor = { version = "0.13.0", path = "../../../client/executor" }
sc-service = { version = "0.17.0", features = [
	"test-helpers",
	"rocksdb",
], path = "../../../client/service" }
sp-api = { version = "7.0.0", path = "../../../primitives/api" }
sp-block-builder = { version = "7.0.0", path = "../../../primitives/block-builder" }
sp-blockchain = { version = "9.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.13.0", path = "../../../primitives/consensus/common" }
sp-core = { version = "10.0.0", path = "../../../primitives/core" }
sp-inherents = { version = "7.0.0", path = "../../../primitives/inherents" }
sp-io = { version = "11.0.0", path = "../../../primitives/io" }
sp-keyring = { version = "11.0.0", path = "../../../primitives/keyring" }
sp-runtime = { version = "11.0.0", path = "../../../primitives/runtime" }
sp-timestamp = { version = "7.0.0", default-features = false, path = "../../../primitives/timestamp" }
substrate-test-client = { version = "2.0.0", path = "../../../test-utils/client" }
