[package]
name = "node-template"
version = "4.0.0-dev"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
homepage = "https://substrate.io/"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-template"

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
futures = { version = "0.3.21", features = ["thread-pool"]}

sc-cli = { version = "0.18.0", path = "../../../client/cli" }
sp-core = { version = "10.0.0", path = "../../../primitives/core" }
sc-executor = { version = "0.13.0", path = "../../../client/executor" }
sc-service = { version = "0.17.0", path = "../../../client/service" }
sc-telemetry = { version = "5.0.0", path = "../../../client/telemetry" }
sc-keystore = { version = "7.0.0", path = "../../../client/keystore" }
sc-transaction-pool = { version = "10.0.0", path = "../../../client/transaction-pool" }
sc-transaction-pool-api = { version = "9.0.0", path = "../../../client/transaction-pool/api" }
sc-consensus-aura = { version = "0.16.0", path = "../../../client/consensus/aura" }
sp-consensus-aura = { version = "0.13.0", path = "../../../primitives/consensus/aura" }
sp-consensus = { version = "0.13.0", path = "../../../primitives/consensus/common" }
sc-consensus = { version = "0.15.0", path = "../../../client/consensus/common" }
sc-finality-grandpa = { version = "0.16.0", path = "../../../client/finality-grandpa" }
sp-finality-grandpa = { version = "7.0.0", path = "../../../primitives/finality-grandpa" }
sc-client-api = { version = "9.0.0", path = "../../../client/api" }
sp-runtime = { version = "11.0.0", path = "../../../primitives/runtime" }
sp-io = { version = "11.0.0", path = "../../../primitives/io" }
sp-timestamp = { version = "7.0.0", path = "../../../primitives/timestamp" }
sp-inherents = { version = "7.0.0", path = "../../../primitives/inherents" }
sp-keyring = { version = "11.0.0", path = "../../../primitives/keyring" }
frame-system = { version = "9.0.0", path = "../../../frame/system" }
pallet-transaction-payment = { version = "9.0.0", default-features = false, path = "../../../frame/transaction-payment" }

# These dependencies are used for the node template's RPCs
jsonrpsee = { version = "0.16.2", features = ["server"] }
sc-rpc = { version = "11.0.0", path = "../../../client/rpc" }
sp-api = { version = "7.0.0", path = "../../../primitives/api" }
sc-rpc-api = { version = "0.15.0", path = "../../../client/rpc-api" }
sp-blockchain = { version = "9.0.0", path = "../../../primitives/blockchain" }
sp-block-builder = { version = "7.0.0", path = "../../../primitives/block-builder" }
sc-basic-authorship = { version = "0.16.0", path = "../../../client/basic-authorship" }
substrate-frame-rpc-system = { version = "10.0.0", path = "../../../utils/frame/rpc/system" }
pallet-transaction-payment-rpc = { version = "11.0.0", path = "../../../frame/transaction-payment/rpc/" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "9.0.0", path = "../../../frame/benchmarking" }
frame-benchmarking-cli = { version = "14.0.0", path = "../../../utils/frame/benchmarking-cli" }

# Local Dependencies
node-template-runtime = { version = "4.0.0-dev", path = "../runtime" }

# CLI-specific dependencies
try-runtime-cli = { version = "0.20.0", optional = true, path = "../../../utils/frame/try-runtime/cli" }

[build-dependencies]
substrate-build-script-utils = { version = "4.0.0", path = "../../../utils/build-script-utils" }

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
	"node-template-runtime/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["node-template-runtime/try-runtime", "try-runtime-cli/try-runtime"]
