[package]
name = "node-executor"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
scale-info = { version = "2.1.1", features = ["derive"] }
frame-benchmarking = { version = "9.0.0", path = "../../../frame/benchmarking" }
node-primitives = { version = "2.0.0", path = "../primitives" }
kitchensink-runtime = { version = "3.0.0-dev", path = "../runtime" }
sc-executor = { version = "0.13.0", path = "../../../client/executor" }
sp-core = { version = "10.0.0", path = "../../../primitives/core" }
sp-keystore = { version = "0.16.0", path = "../../../primitives/keystore" }
sp-state-machine = { version = "0.16.0", path = "../../../primitives/state-machine" }
sp-tracing = { version = "7.0.0", path = "../../../primitives/tracing" }
sp-trie = { version = "10.0.0", path = "../../../primitives/trie" }

[dev-dependencies]
criterion = "0.3.0"
futures = "0.3.21"
wat = "1.0"
frame-support = { version = "9.0.0", path = "../../../frame/support" }
frame-system = { version = "9.0.0", path = "../../../frame/system" }
node-testing = { version = "3.0.0-dev", path = "../testing" }
pallet-balances = { version = "9.0.0", path = "../../../frame/balances" }
pallet-contracts = { version = "9.0.0", path = "../../../frame/contracts" }
pallet-im-online = { version = "9.0.0", path = "../../../frame/im-online" }
pallet-sudo = { version = "9.0.0", path = "../../../frame/sudo" }
pallet-timestamp = { version = "9.0.0", path = "../../../frame/timestamp" }
pallet-treasury = { version = "9.0.0", path = "../../../frame/treasury" }
pallet-transaction-payment = { version = "9.0.0", path = "../../../frame/transaction-payment" }
sp-application-crypto = { version = "11.0.0", path = "../../../primitives/application-crypto" }
pallet-root-testing = { version = "1.0.0-dev", path = "../../../frame/root-testing" }
sp-consensus-babe = { version = "0.13.0", path = "../../../primitives/consensus/babe" }
sp-externalities = { version = "0.15.0", path = "../../../primitives/externalities" }
sp-keyring = { version = "11.0.0", path = "../../../primitives/keyring" }
sp-runtime = { version = "11.0.0", path = "../../../primitives/runtime" }

[features]
stress-test = []

[[bench]]
name = "bench"
harness = false
